"""initial_schema

Revision ID: 11a232827345
Revises: 
Create Date: 2026-06-09 06:22:49.871783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a232827345'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('free_margin', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_created_at'), 'account_snapshots', ['created_at'], unique=False)
    op.create_table('ai_advisor_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', 'HOLD', name='aiside'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('market_context', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_advisor_suggestions_symbol'), 'ai_advisor_suggestions', ['symbol'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('initial_equity', sa.Float(), nullable=False),
    sa.Column('final_equity', sa.Float(), nullable=True),
    sa.Column('net_pnl_r', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('n_bars', sa.Integer(), nullable=True),
    sa.Column('n_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('sharpe_approx', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('drawdown_curve', sa.JSON(), nullable=True),
    sa.Column('monthly_returns', sa.JSON(), nullable=True),
    sa.Column('params_snapshot', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_status'), 'backtest_runs', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_runs_strategy_name'), 'backtest_runs', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_backtest_runs_symbol'), 'backtest_runs', ['symbol'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'TESTING', 'ACCEPTED', 'REJECTED', name='hypothesisstatus'), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('hypothesis_text', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('test_result', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_status'), 'hypotheses', ['status'], unique=False)
    op.create_index(op.f('ix_hypotheses_symbol'), 'hypotheses', ['symbol'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_type', sa.Enum('RANDOM_FOREST', 'GRADIENT_BOOSTING', 'LOGISTIC', name='modeltype'), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('feature_columns', sa.JSON(), nullable=True),
    sa.Column('hyperparams', sa.JSON(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('n_train_samples', sa.Integer(), nullable=True),
    sa.Column('last_trained_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_name'), 'ml_models', ['name'], unique=False)
    op.create_index(op.f('ix_ml_models_symbol'), 'ml_models', ['symbol'], unique=False)
    op.create_table('ohlcv_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('tick_volume', sa.Integer(), nullable=True),
    sa.Column('spread', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_ohlcv_symbol_tf_ts')
    )
    op.create_index(op.f('ix_ohlcv_bars_symbol'), 'ohlcv_bars', ['symbol'], unique=False)
    op.create_index(op.f('ix_ohlcv_bars_timestamp'), 'ohlcv_bars', ['timestamp'], unique=False)
    op.create_index('ix_ohlcv_symbol_tf_ts', 'ohlcv_bars', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_settings_key'), 'platform_settings', ['key'], unique=True)
    op.create_table('strategy_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('param_bounds', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'symbol', 'timeframe', name='uq_strategy_symbol_tf')
    )
    op.create_index('ix_strategy_active', 'strategy_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_strategy_configs_symbol'), 'strategy_configs', ['symbol'], unique=False)
    op.create_index(op.f('ix_strategy_configs_timeframe'), 'strategy_configs', ['timeframe'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('strategy_param_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_config_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['strategy_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_param_versions_strategy_config_id'), 'strategy_param_versions', ['strategy_config_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='side'), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('tp1', sa.Float(), nullable=True),
    sa.Column('tp2', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_r', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=True),
    sa.Column('ai_suggestion_id', sa.Integer(), nullable=True),
    sa.Column('account_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('closed_reason', sa.String(length=64), nullable=True),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_snapshot_id'], ['account_snapshots.id'], ),
    sa.ForeignKeyConstraint(['ai_suggestion_id'], ['ai_advisor_suggestions.id'], ),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_ai_suggestion_id'), 'trades', ['ai_suggestion_id'], unique=False)
    op.create_index(op.f('ix_trades_backtest_run_id'), 'trades', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_trades_source'), 'trades', ['source'], unique=False)
    op.create_index('ix_trades_strategy', 'trades', ['strategy_name', 'symbol', 'timeframe'], unique=False)
    op.create_index(op.f('ix_trades_strategy_name'), 'trades', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index('ix_trades_symbol_opened', 'trades', ['symbol', 'opened_at'], unique=False)
    op.create_index(op.f('ix_trades_ticket'), 'trades', ['ticket'], unique=False)
    op.create_table('trade_annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_annotations_trade_id'), 'trade_annotations', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_annotations_trade_id'), table_name='trade_annotations')
    op.drop_table('trade_annotations')
    op.drop_index(op.f('ix_trades_ticket'), table_name='trades')
    op.drop_index('ix_trades_symbol_opened', table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_name'), table_name='trades')
    op.drop_index('ix_trades_strategy', table_name='trades')
    op.drop_index(op.f('ix_trades_source'), table_name='trades')
    op.drop_index(op.f('ix_trades_backtest_run_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_ai_suggestion_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_strategy_param_versions_strategy_config_id'), table_name='strategy_param_versions')
    op.drop_table('strategy_param_versions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_strategy_configs_timeframe'), table_name='strategy_configs')
    op.drop_index(op.f('ix_strategy_configs_symbol'), table_name='strategy_configs')
    op.drop_index('ix_strategy_active', table_name='strategy_configs')
    op.drop_table('strategy_configs')
    op.drop_index(op.f('ix_platform_settings_key'), table_name='platform_settings')
    op.drop_table('platform_settings')
    op.drop_index('ix_ohlcv_symbol_tf_ts', table_name='ohlcv_bars')
    op.drop_index(op.f('ix_ohlcv_bars_timestamp'), table_name='ohlcv_bars')
    op.drop_index(op.f('ix_ohlcv_bars_symbol'), table_name='ohlcv_bars')
    op.drop_table('ohlcv_bars')
    op.drop_index(op.f('ix_ml_models_symbol'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_name'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_hypotheses_symbol'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_status'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_backtest_runs_symbol'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_strategy_name'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_status'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_ai_advisor_suggestions_symbol'), table_name='ai_advisor_suggestions')
    op.drop_table('ai_advisor_suggestions')
    op.drop_index(op.f('ix_account_snapshots_created_at'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
