"""add backtestrunn error_message column

Revision ID: 28067535852e
Revises: f23152f474a8
Create Date: 2026-06-11 06:51:36.209964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28067535852e'
down_revision: Union[str, Sequence[str], None] = 'f23152f474a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'account_type',
               existing_type=postgresql.ENUM('live', 'demo', name='accounttype'),
               type_=sa.String(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'demo'::accounttype"))
    op.add_column('backtest_runs', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_runs', 'error_message')
    op.alter_column('accounts', 'account_type',
               existing_type=sa.String(length=8),
               type_=postgresql.ENUM('live', 'demo', name='accounttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'demo'::accounttype"))
    # ### end Alembic commands ###
