"""add status and feature_importance to ml_models

Revision ID: ce6c64e55d52
Revises: d7a7e85b8728
Create Date: 2026-06-12 17:28:37.533723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6c64e55d52'
down_revision: Union[str, Sequence[str], None] = 'd7a7e85b8728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_models', sa.Column('status', sa.String(length=16), nullable=False))
    op.add_column('ml_models', sa.Column('feature_importance', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_ml_models_status'), 'ml_models', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_models_status'), table_name='ml_models')
    op.drop_column('ml_models', 'feature_importance')
    op.drop_column('ml_models', 'status')
    # ### end Alembic commands ###
